#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Ensure we execute commands from the frontend directory
cd "$(dirname "$0")/.."

# Enforce Conventional Commits using commitlint
npx --no-install commitlint --edit "$1"

