name: Storybook and Tests

on:
  push:
    branches: [main, master, staging, dev]
  pull_request:
    branches: ["**"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Unit tests with coverage
        run: npm run test:coverage

      - name: E2E summary (JSON)
        run: npm run test:e2e:json

      - name: E2E HTML report
        run: npm run test:e2e

      - name: Storybook UI checks (Playwright)
        run: npm run test:sb

      - name: Build Storybook
        run: npm run build-storybook

      - name: Write pages.json (candidate URL)
        shell: bash
        run: |
          OWNER="${GITHUB_REPOSITORY%/*}"
          REPO="${GITHUB_REPOSITORY#*/}"
          mkdir -p storybook-static
          cat > storybook-static/pages.json <<EOF
          {"owner":"$OWNER","repo":"$REPO","candidate":"https://$OWNER.github.io/$REPO/"}
          EOF

      - name: Upload Storybook Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: coverage/
          if-no-files-found: ignore

      - name: Upload Playwright summary JSON
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-summary
          path: public/playwright-summary.json
          if-no-files-found: ignore

      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          if-no-files-found: ignore

      - name: Upload Storybook static build
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: storybook-static
          path: storybook-static/
          if-no-files-found: ignore

  deploy:
    needs: ci
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
