name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main, master, staging, dev ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    working-directory: frontend

jobs:
  commitlint:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Commitlint (PR commits)
        uses: wagoid/commitlint-github-action@v5

  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 35

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run type-check

      - name: Lint
        run: npm run lint

      - name: Run unit tests with coverage
        run: npm test -- --ci --coverage

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: frontend/coverage

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests (mock mode)
        env:
          CI: 'true'
        run: npx playwright test

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report

      - name: Build Storybook
        run: npm run build-storybook

      - name: Run Storybook Test Runner
        run: npm run storybook:test

      - name: Upload Storybook static as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: frontend/storybook-static

      - name: Upload Storybook Pages artifact (for deploy)
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/storybook-static

      - name: Link check docs (optional)
        if: ${{ !cancelled() }}
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress docs/**/*.md frontend/docs/**/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Chromatic step removed - uncomment if you have CHROMATIC_PROJECT_TOKEN secret
      # - name: Publish to Chromatic (optional)
      #   uses: chromaui/action@v1
      #   with:
      #     projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     workingDir: frontend

  deploy:
    needs: build-and-test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

